# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'try7' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for try7
  pod "VK-ios-sdk" 

  target 'try7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'try7UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
