# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'AMadopter' do
	pod 'SwiftyJSON'
	pod 'PubNub'
	pod 'Alamofire', '~> 4.4'
        pod 'SwiftyVK', :git => 'https://github.com/WE-St0r/SwiftyVK.git'
end